/// AWStats web log statistics generator.
///
/// AWStats reads the Combined Log Format access log produced by OpenLiteSpeed,
/// writes a per-domain config file, and outputs static HTML pages.
use super::{shell, ServiceError};
use std::path::Path;
use tokio::fs;
use tracing::info;

const AWSTATS_CONF_DIR: &str = "/etc/awstats";
const AWSTATS_DATA_DIR: &str = "/var/lib/awstats";

/// Return true if the awstats script exists on this system.
pub async fn is_installed() -> bool {
    shell::command_exists("awstats").await
        || Path::new("/usr/lib/cgi-bin/awstats.pl").exists()
        || Path::new("/usr/share/awstats/tools/awstats.pl").exists()
}

/// Resolve the path to the awstats.pl script.
fn awstats_pl() -> &'static str {
    if Path::new("/usr/lib/cgi-bin/awstats.pl").exists() {
        "/usr/lib/cgi-bin/awstats.pl"
    } else {
        "/usr/share/awstats/tools/awstats.pl"
    }
}

/// Install AWStats via apt-get.
pub async fn install() -> Result<(), ServiceError> {
    info!("Installing AWStats...");
    shell::exec("apt-get", &["install", "-y", "awstats"]).await?;
    info!("AWStats installed");
    Ok(())
}

/// Write an AWStats config file for the given domain.
async fn write_config(domain: &str, access_log: &str) -> Result<String, ServiceError> {
    let conf_path = format!("{}/awstats.{}.conf", AWSTATS_CONF_DIR, domain);

    // Only create if it doesn't exist yet (avoid overwriting manual edits)
    if !Path::new(&conf_path).exists() {
        let contents = format!(
            r#"# AWStats config generated by web panel for {domain}
LogFile="{access_log}"
LogFormat=1
SiteDomain="{domain}"
AllowToFollowSymbolicLinks=1
DirData="{AWSTATS_DATA_DIR}"
DirCgi="/usr/lib/cgi-bin"
DirIcons="/usr/share/awstats/icon"
AllowFullYearView=3
EnableLockForUpdate=1
LevelForBrowsersDetection=2
LevelForOSDetection=2
LevelForRefererAnalyze=2
LevelForRobotsDetection=2
LevelForSearchEnginesDetection=2
LevelForKeywordsDetection=2
LevelForFileTypesDetection=2
LevelForWormsDetection=0
UseFramesWhenCGI=1
UseMenuSubFrameIfPossible=1
UpdateIfNo404=1
BuildHistoryFormat=text
BuildReportFormat=html
ShowDaysOfMonthStats=HB
ShowDaysOfWeekStats=HB
ShowHoursStats=HB
ShowMonthStats=UVPHBZ
ShowDomainStats=PHB
ShowHostsStats=PHBL
"#
        );
        fs::create_dir_all(AWSTATS_CONF_DIR)
            .await
            .map_err(|e| ServiceError::IoError(e.to_string()))?;
        let tmp_conf = format!("{}.tmp.{}", conf_path, std::process::id());
        fs::write(&tmp_conf, contents)
            .await
            .map_err(|e| ServiceError::IoError(e.to_string()))?;
        fs::rename(&tmp_conf, &conf_path)
            .await
            .map_err(|e| ServiceError::IoError(e.to_string()))?;
    }

    // Ensure data directory exists
    fs::create_dir_all(AWSTATS_DATA_DIR)
        .await
        .map_err(|e| ServiceError::IoError(e.to_string()))?;

    Ok(conf_path)
}

/// Build AWStats static HTML output into `output_dir`.
async fn build_static(domain: &str, output_dir: &str) -> Result<(), ServiceError> {
    let build_script = "/usr/share/awstats/tools/awstats_buildstaticpages.pl";
    if !Path::new(build_script).exists() {
        // Fallback: just update data, no static pages
        return Ok(());
    }

    shell::exec(
        "perl",
        &[
            build_script,
            &format!("-config={}", domain),
            &format!("-dir={}", output_dir),
            "-awstatsprog=/usr/lib/cgi-bin/awstats.pl",
        ],
    )
    .await?;
    Ok(())
}

/// Generate AWStats statistics for a domain.
///
/// * `access_log`  – path to OLS combined-format access log
/// * `output_dir`  – directory where static HTML pages are written
/// * `domain`      – the virtual host name (also used as config key)
pub async fn generate(
    access_log: &str,
    output_dir: &str,
    domain: &str,
) -> Result<(), ServiceError> {
    if !is_installed().await {
        return Err(ServiceError::NotInstalled);
    }

    crate::utils::validators::validate_domain(domain)
        .map_err(|e| ServiceError::CommandFailed(e.to_string()))?;
    crate::utils::validators::validate_safe_path(access_log, "/usr/local/lsws/logs/")
        .map_err(|e| ServiceError::CommandFailed(e.to_string()))?;
    crate::utils::validators::validate_safe_path(output_dir, "/var/www/")
        .map_err(|e| ServiceError::CommandFailed(e.to_string()))?;

    if !Path::new(access_log).exists() {
        return Err(ServiceError::IoError(format!(
            "Access log not found: {access_log}"
        )));
    }

    // Ensure output directory exists
    fs::create_dir_all(output_dir)
        .await
        .map_err(|e| ServiceError::IoError(e.to_string()))?;

    write_config(domain, access_log).await?;

    let pl = awstats_pl();
    info!("Running AWStats update for {}", domain);

    shell::exec("perl", &[pl, &format!("-config={}", domain), "-update"]).await?;

    build_static(domain, output_dir).await?;

    info!("AWStats report generated for {}", domain);
    Ok(())
}
